version: '3'

services:
    jupyter:
        build: .
        ports:
            - "8888:8888"
        volumes:
            - "./src/data:/tf/notebook/data"
            - "./src/notebooks/MNIST.ipynb:/tf/notebook/MNIST.ipynb"